<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>504ded81-fced-4986-bb2c-adb94600eb5a</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="MimeKit" Version="4.13.0" />
  </ItemGroup>
</Project>
